version: '3.8'

services:
  mysqldb:
    container_name: sms-db
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=mysql
      - MYSQL_TCP_PORT=3307
      - VIRTUAL_PORT=3307
    image: mysql
    ports:
      - '3307:3307'
    expose:
      - 3307
    volumes:
      - mysqldb_data:/data/db

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: sms-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev
    volumes:
      - .:/opt/jboss/keycloak/imports

volumes:
  mysqldb_data: